# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDWebImage Image Download URL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImage Image Download URL
	pod 'SDWebImage'

end
